name: tubes_iot
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  noise_meter: ^3.0.1
  syncfusion_flutter_charts: ^19.1.67
  geekyants_flutter_gauges: 1.0.1
  google_fonts: ^2.1.0
  path_provider: ^2.0.15
  csv: ^5.0.2
  permission_handler: ^7.1.0
  open_file_plus: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
